package interfaz;

import database.HelperDB;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * isssteEZCAN
 * Departamento de Investigación en Biología Molecular y Medicina Genómica 
 * Hospital Regional "Lic. Adolfo López Mateos" ISSSTE
 * Desarrollador: IB Juan José Guzmán Cruz
 * Responsable del proyecto: DC Osvaldo Erick Sánchez Hernández
 */
public class Principal extends javax.swing.JFrame {
    
    private final HelperDB helper;
    private final DefaultTableModel model;
    private final Tablas tablas;
    private final Date date, time;
    private final Personales personales;
    
    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        
        helper = new HelperDB();
        model = new DefaultTableModel();
        tablas = new Tablas();
        
        date = new Date();
        time = new Date();
        
        personales = new Personales(new javax.swing.JFrame(), true);
        
        this.setExtendedState(this.MAXIMIZED_BOTH);
        this.setLocationRelativeTo(null);
        this.ponerFechaHora();
        this.iniciarTabla();
        this.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bgSexo = new javax.swing.ButtonGroup();
        bgTipo = new javax.swing.ButtonGroup();
        bgFuma = new javax.swing.ButtonGroup();
        bgAlcohol = new javax.swing.ButtonGroup();
        bgInfartos = new javax.swing.ButtonGroup();
        bgInfartoPrevio = new javax.swing.ButtonGroup();
        bgEVC = new javax.swing.ButtonGroup();
        bgAnginaPrevia = new javax.swing.ButtonGroup();
        bgHipoglicemiantes = new javax.swing.ButtonGroup();
        bgHipolipemiantes = new javax.swing.ButtonGroup();
        dMarcador = new javax.swing.JDialog();
        tfGenotipo = new javax.swing.JTextField();
        tfGenotipoCodigo = new javax.swing.JTextField();
        lMarcador = new javax.swing.JLabel();
        tfDominante = new javax.swing.JTextField();
        lAlelo1 = new javax.swing.JLabel();
        tfDominanteCodigo = new javax.swing.JTextField();
        lAlelo2 = new javax.swing.JLabel();
        lRiesgo = new javax.swing.JLabel();
        tfConf2 = new javax.swing.JTextField();
        tfConf3 = new javax.swing.JTextField();
        lGencod = new javax.swing.JLabel();
        tfMarcador = new javax.swing.JTextField();
        lDominante = new javax.swing.JLabel();
        lConfig1 = new javax.swing.JLabel();
        lConfig2 = new javax.swing.JLabel();
        bCalcular = new javax.swing.JButton();
        lConfig3 = new javax.swing.JLabel();
        tfAlelo1 = new javax.swing.JTextField();
        lGenotipo = new javax.swing.JLabel();
        lDomCod = new javax.swing.JLabel();
        tfAlelo2 = new javax.swing.JTextField();
        tfRiesgo = new javax.swing.JTextField();
        tfConf1 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfRecesivo = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        tfRecesivoCodigo = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        tfAditivoCodigo = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        bEditar = new javax.swing.JButton();
        bSalir = new javax.swing.JButton();
        bAgregar = new javax.swing.JButton();
        bEliminar = new javax.swing.JButton();
        bBuscar = new javax.swing.JButton();
        bImprimir = new javax.swing.JButton();
        bPruebas = new javax.swing.JButton();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        tDatos = new javax.swing.JTable();
        lFecha = new javax.swing.JLabel();
        lHora = new javax.swing.JLabel();
        mbPrincipal = new javax.swing.JMenuBar();
        mArchivo = new javax.swing.JMenu();
        mInsertar = new javax.swing.JMenu();
        miMarcador = new javax.swing.JMenuItem();

        dMarcador.setAlwaysOnTop(true);
        dMarcador.setMinimumSize(new java.awt.Dimension(1200, 300));
        dMarcador.setModal(true);

        tfGenotipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfGenotipo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfGenotipo.setEnabled(false);
        tfGenotipo.setOpaque(false);

        tfGenotipoCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfGenotipoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfGenotipoCodigo.setEnabled(false);
        tfGenotipoCodigo.setOpaque(false);

        lMarcador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lMarcador.setText("MARCADOR");

        tfDominante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfDominante.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDominante.setEnabled(false);
        tfDominante.setOpaque(false);

        lAlelo1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lAlelo1.setText("ALELO 1");

        tfDominanteCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfDominanteCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDominanteCodigo.setEnabled(false);
        tfDominanteCodigo.setOpaque(false);

        lAlelo2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lAlelo2.setText("ALELO2");

        lRiesgo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lRiesgo.setText("RIESGO");

        tfConf2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfConf2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfConf3.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfConf3.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lGencod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lGencod.setText("<html>Genotipo<li>código</li></html>");

        tfMarcador.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfMarcador.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lDominante.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lDominante.setText("DOMINANTE");

        lConfig1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lConfig1.setText("CONF1");

        lConfig2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lConfig2.setText("CONF2");

        bCalcular.setText("Calcular");
        bCalcular.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bCalcularMouseReleased(evt);
            }
        });

        lConfig3.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lConfig3.setText("CONF3");

        tfAlelo1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfAlelo1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        lGenotipo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lGenotipo.setText("GENOTIPO");

        lDomCod.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        lDomCod.setText("<html>Dominante<li>código</li></html>");

        tfAlelo2.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfAlelo2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfRiesgo.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfRiesgo.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        tfConf1.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        tfConf1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel8.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel8.setText("RECESIVO");

        tfRecesivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfRecesivo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRecesivo.setEnabled(false);
        tfRecesivo.setOpaque(false);

        jLabel15.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel15.setText("<html>Recesivo<li>código</li></html>");

        tfRecesivoCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfRecesivoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfRecesivoCodigo.setEnabled(false);
        tfRecesivoCodigo.setOpaque(false);

        jLabel16.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel16.setText("<html>Aditivo<li>código</li></html>");

        tfAditivoCodigo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        tfAditivoCodigo.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfAditivoCodigo.setEnabled(false);
        tfAditivoCodigo.setOpaque(false);

        javax.swing.GroupLayout dMarcadorLayout = new javax.swing.GroupLayout(dMarcador.getContentPane());
        dMarcador.getContentPane().setLayout(dMarcadorLayout);
        dMarcadorLayout.setHorizontalGroup(
            dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dMarcadorLayout.createSequentialGroup()
                .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dMarcadorLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lMarcador, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfMarcador))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lConfig1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfConf1))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lConfig2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfConf2))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lConfig3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfConf3))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lAlelo1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfAlelo1))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfAlelo2)
                            .addComponent(lAlelo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRiesgo)
                            .addComponent(lRiesgo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lGenotipo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfGenotipo))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lGencod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfGenotipoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lDominante)
                            .addComponent(tfDominante, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfDominanteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lDomCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel8)
                            .addComponent(tfRecesivo, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel15)
                            .addComponent(tfRecesivoCodigo))
                        .addGap(15, 15, 15)
                        .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel16)
                            .addComponent(tfAditivoCodigo)))
                    .addGroup(dMarcadorLayout.createSequentialGroup()
                        .addGap(425, 425, 425)
                        .addComponent(bCalcular)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        dMarcadorLayout.setVerticalGroup(
            dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dMarcadorLayout.createSequentialGroup()
                .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lMarcador)
                    .addComponent(lAlelo1)
                    .addComponent(lAlelo2)
                    .addComponent(lRiesgo)
                    .addComponent(lDominante)
                    .addComponent(lConfig1)
                    .addComponent(lConfig2)
                    .addComponent(lConfig3)
                    .addComponent(lGenotipo)
                    .addComponent(lGencod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lDomCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(dMarcadorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfConf2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConf1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfConf3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlelo1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAlelo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRiesgo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGenotipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfGenotipoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDominante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfDominanteCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfMarcador, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRecesivo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfRecesivoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfAditivoCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(95, 95, 95)
                .addComponent(bCalcular)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("isssteEZCAN");
        setMinimumSize(new java.awt.Dimension(1200, 800));
        setPreferredSize(new java.awt.Dimension(1200, 800));

        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        bEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_editar.png"))); // NOI18N

        bSalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_salir.png"))); // NOI18N
        bSalir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bSalirMouseReleased(evt);
            }
        });

        bAgregar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_agregar_nuevo.png"))); // NOI18N
        bAgregar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bAgregarMouseReleased(evt);
            }
        });

        bEliminar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_eliminar.png"))); // NOI18N

        bBuscar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_buscar.png"))); // NOI18N
        bBuscar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bBuscarMouseReleased(evt);
            }
        });

        bImprimir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagenes/ic_imprimir.png"))); // NOI18N
        bImprimir.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bImprimirMouseReleased(evt);
            }
        });

        bPruebas.setText("Pruebas");
        bPruebas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                bPruebasMouseReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(bAgregar)
                .addGap(50, 50, 50)
                .addComponent(bEditar)
                .addGap(50, 50, 50)
                .addComponent(bEliminar)
                .addGap(80, 80, 80)
                .addComponent(bPruebas)
                .addGap(76, 76, 76)
                .addComponent(bBuscar)
                .addGap(50, 50, 50)
                .addComponent(bImprimir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 114, Short.MAX_VALUE)
                .addComponent(bSalir)
                .addGap(50, 50, 50))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bSalir, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEditar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bBuscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bImprimir, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bAgregar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(44, 44, 44)
                .addComponent(bPruebas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane1.setAutoscrolls(true);
        jScrollPane1.setMaximumSize(new java.awt.Dimension(327670, 327670));

        tDatos.setAutoCreateRowSorter(true);
        tDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(tDatos);

        lFecha.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lFecha.setForeground(new java.awt.Color(255, 255, 255));

        lHora.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        lHora.setForeground(new java.awt.Color(255, 255, 255));

        jDesktopPane1.setLayer(jScrollPane1, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lFecha, javax.swing.JLayeredPane.DEFAULT_LAYER);
        jDesktopPane1.setLayer(lHora, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jDesktopPane1Layout = new javax.swing.GroupLayout(jDesktopPane1);
        jDesktopPane1.setLayout(jDesktopPane1Layout);
        jDesktopPane1Layout.setHorizontalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDesktopPane1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(165, 165, 165)
                        .addComponent(lHora, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jDesktopPane1Layout.setVerticalGroup(
            jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDesktopPane1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 570, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jDesktopPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lHora, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jDesktopPane1Layout.createSequentialGroup()
                        .addComponent(lFecha, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );

        mbPrincipal.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        mArchivo.setText("Archivo");
        mArchivo.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        mbPrincipal.add(mArchivo);

        mInsertar.setText("Insertar");
        mInsertar.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        miMarcador.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        miMarcador.setText("Marcador");
        miMarcador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                miMarcadorActionPerformed(evt);
            }
        });
        mInsertar.add(miMarcador);

        mbPrincipal.add(mInsertar);

        setJMenuBar(mbPrincipal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jDesktopPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jDesktopPane1)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
private void bAgregarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bAgregarMouseReleased
        this.personales.setTitle("Nuevo registro");
        this.personales.setVisible(true);
    }//GEN-LAST:event_bAgregarMouseReleased

    private void bSalirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bSalirMouseReleased
        System.exit(0);
    }//GEN-LAST:event_bSalirMouseReleased

    private void bBuscarMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bBuscarMouseReleased
        //String query = JOptionPane.showInputDialog(this, "Query", "SELECT * FROM Personales LEFT JOIN Antecedentes ON Personales.reg_paciente = Antecedentes.reg_paciente GROUP BY 'reg_paciente'");
        //String query = JOptionPane.showInputDialog(this, "Query", "SELECT * FROM Personales JOIN Antecedentes ON Personales.reg_paciente = Antecedentes.reg_paciente");
        //String query = JOptionPane.showInputDialog(this, "Query", "SELECT * FROM Personales, Antecedentes WHERE Personales.reg_paciente = Antecedentes.reg_paciente");
        String query = JOptionPane.showInputDialog(this, "Query", "SELECT * FROM Marcadores");
        if(!query.isEmpty()){
            this.tablas.limpiarTabla(this.tDatos);
            this.helper.setColumns(this.model, this.tDatos, query);
            this.helper.setData(this.model, this.tDatos, query);            
        }
    }//GEN-LAST:event_bBuscarMouseReleased

    private void bImprimirMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bImprimirMouseReleased
        
    }//GEN-LAST:event_bImprimirMouseReleased

    private void miMarcadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_miMarcadorActionPerformed
        this.dMarcador.setLocationRelativeTo(null);
        this.dMarcador.setVisible(true);
    }//GEN-LAST:event_miMarcadorActionPerformed

    private void bCalcularMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bCalcularMouseReleased
        calcularMarcador();
    }//GEN-LAST:event_bCalcularMouseReleased

    private void bPruebasMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_bPruebasMouseReleased
        Pruebas pruebas = new Pruebas(new javax.swing.JFrame(), true);
        pruebas.setVisible(true);
    }//GEN-LAST:event_bPruebasMouseReleased
    
    /**
     * Llenar un JTable con condiciones iniciales
     */
    private void iniciarTabla(){
        ArrayList<String> mostrar_tablas = new ArrayList();
        mostrar_tablas.add("Personales");
        mostrar_tablas.add("Antecedentes");
        mostrar_tablas.add("Bioquimica");
        mostrar_tablas.add("Marcadores");
        
        this.helper.setAllModels(this.model, this.tDatos, mostrar_tablas);
        String query = this.helper.getQuery();
        
        this.helper.setData(this.model, this.tDatos, query);
        
        this.tablas.ajustarColumnas(this.tDatos);
    }
    
    /**
     * Agregar los datos Fecha y Hora a dos JLabel
     */
    private void ponerFechaHora(){
        SimpleDateFormat sdf_fecha = new SimpleDateFormat("EEEE dd 'de' MMMM 'del' yyyy");
        SimpleDateFormat sdf_hora = new SimpleDateFormat("HH:mm");
        
        String fecha = sdf_fecha.format(this.date);
        String hora = sdf_hora.format(this.time);
        
        this.lFecha.setText(fecha);
        this.lHora.setText(hora);
    }
    
    /**
     * Calcula valores para el componente JDialog dMarcadores
     */
    private void calcularMarcador(){
        String marcador = this.tfMarcador.getText();
        String conf1 = this.tfConf1.getText();
        String conf2 = this.tfConf2.getText();
        String conf3 = this.tfConf3.getText();
        String alelo1 = this.tfAlelo1.getText();
        String alelo2 = this.tfAlelo2.getText();
        String riesgo = this.tfRiesgo.getText();

        // Genotipo
        String genotipo = alelo1 + alelo2;
        this.tfGenotipo.setText(genotipo);

        // Genotipo código
        String genotipo_codigo = "";
        if(genotipo.equals(conf1)){
            genotipo_codigo = "1";
        }
        else if(genotipo.equals(conf2)){
            genotipo_codigo = "2";
        }
        if(genotipo.equals(conf3)){
            genotipo_codigo = "3";
        }
        this.tfGenotipoCodigo.setText(genotipo_codigo);

        // Dominante y Dominante código
        this.tfDominante.setText(conf1 + " + " + conf2 + " vs " + conf3);
        String dominante_codigo = "0";
        if(genotipo.equals(conf1) || genotipo.equals(conf2)){
            dominante_codigo = "1";
        }
        this.tfDominanteCodigo.setText(dominante_codigo);

        // Recesivo y Recesivo código
        this.tfRecesivo.setText(conf1 + " vs " + conf2 + " + " + conf3);
        String recesivo_codigo = "0";
        if(genotipo.equals(conf1)){
            recesivo_codigo = "1";
        }
        this.tfRecesivoCodigo.setText(recesivo_codigo);

        // Aditivo y Aditivo código
        String aditivo_codigo = "";
        if(genotipo.equals(conf1)){
            aditivo_codigo = "2";
        }
        else if(genotipo.equals(conf2)){
            aditivo_codigo = "1";
        }
        if(genotipo.equals(conf3)){
            aditivo_codigo = "0";
        }
        this.tfAditivoCodigo.setText(aditivo_codigo);
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Principal principal = new Principal();
                /*
                principal.setExtendedState(principal.MAXIMIZED_BOTH);
                principal.setLocationRelativeTo(null);
                principal.ponerFechaHora();
                principal.iniciarTabla();
                principal.setVisible(true);
*/
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bAgregar;
    private javax.swing.JButton bBuscar;
    private javax.swing.JButton bCalcular;
    private javax.swing.JButton bEditar;
    private javax.swing.JButton bEliminar;
    private javax.swing.JButton bImprimir;
    private javax.swing.JButton bPruebas;
    private javax.swing.JButton bSalir;
    private javax.swing.ButtonGroup bgAlcohol;
    private javax.swing.ButtonGroup bgAnginaPrevia;
    private javax.swing.ButtonGroup bgEVC;
    private javax.swing.ButtonGroup bgFuma;
    private javax.swing.ButtonGroup bgHipoglicemiantes;
    private javax.swing.ButtonGroup bgHipolipemiantes;
    private javax.swing.ButtonGroup bgInfartoPrevio;
    private javax.swing.ButtonGroup bgInfartos;
    private javax.swing.ButtonGroup bgSexo;
    private javax.swing.ButtonGroup bgTipo;
    private javax.swing.JDialog dMarcador;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lAlelo1;
    private javax.swing.JLabel lAlelo2;
    private javax.swing.JLabel lConfig1;
    private javax.swing.JLabel lConfig2;
    private javax.swing.JLabel lConfig3;
    private javax.swing.JLabel lDomCod;
    private javax.swing.JLabel lDominante;
    private javax.swing.JLabel lFecha;
    private javax.swing.JLabel lGencod;
    private javax.swing.JLabel lGenotipo;
    private javax.swing.JLabel lHora;
    private javax.swing.JLabel lMarcador;
    private javax.swing.JLabel lRiesgo;
    private javax.swing.JMenu mArchivo;
    private javax.swing.JMenu mInsertar;
    private javax.swing.JMenuBar mbPrincipal;
    private javax.swing.JMenuItem miMarcador;
    private javax.swing.JTable tDatos;
    private javax.swing.JTextField tfAditivoCodigo;
    private javax.swing.JTextField tfAlelo1;
    private javax.swing.JTextField tfAlelo2;
    private javax.swing.JTextField tfConf1;
    private javax.swing.JTextField tfConf2;
    private javax.swing.JTextField tfConf3;
    private javax.swing.JTextField tfDominante;
    private javax.swing.JTextField tfDominanteCodigo;
    private javax.swing.JTextField tfGenotipo;
    private javax.swing.JTextField tfGenotipoCodigo;
    private javax.swing.JTextField tfMarcador;
    private javax.swing.JTextField tfRecesivo;
    private javax.swing.JTextField tfRecesivoCodigo;
    private javax.swing.JTextField tfRiesgo;
    // End of variables declaration//GEN-END:variables
}
